services:
  mongo:
    image: mongo:8
    container_name: mongo
    hostname: ${MONGO_HOST}
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongo-data:/data/db
      - .configuration/mongo/init.js:/docker-entrypoint-initdb.d/init.js

volumes:
  mongo-data:
